<?php
$portal = array(
    "http://www.cqvip.com/Journal/2.shtml",
    "http://www.cqvip.com/Journal/3.shtml",
    "http://www.cqvip.com/Journal/4.shtml",
    "http://www.cqvip.com/Journal/5.shtml",
    "http://www.cqvip.com/Journal/6.shtml",
    "http://www.cqvip.com/Journal/7.shtml",
    "http://www.cqvip.com/Journal/8.shtml",
    "http://www.cqvip.com/Journal/9.shtml",
    "http://www.cqvip.com/Journal/10.shtml",
    "http://www.cqvip.com/Journal/11.shtml",
    "http://www.cqvip.com/Journal/12.shtml",
    "http://www.cqvip.com/Journal/13.shtml",
    "http://www.cqvip.com/Journal/14.shtml",
    "http://www.cqvip.com/Journal/15.shtml",
    "http://www.cqvip.com/Journal/16.shtml",
    "http://www.cqvip.com/Journal/17.shtml",
    "http://www.cqvip.com/Journal/18.shtml",
    "http://www.cqvip.com/Journal/68.shtml",

    "http://www.cqvip.com/Journal/19.shtml",
    "http://www.cqvip.com/Journal/20.shtml",
    "http://www.cqvip.com/Journal/21.shtml",
    "http://www.cqvip.com/Journal/22.shtml",
    "http://www.cqvip.com/Journal/23.shtml",
    "http://www.cqvip.com/Journal/24.shtml",
    "http://www.cqvip.com/Journal/25.shtml",
    "http://www.cqvip.com/Journal/26.shtml",
    "http://www.cqvip.com/Journal/27.shtml",
    "http://www.cqvip.com/Journal/28.shtml",
    "http://www.cqvip.com/Journal/29.shtml",
    "http://www.cqvip.com/Journal/30.shtml",
    "http://www.cqvip.com/Journal/31.shtml",
    "http://www.cqvip.com/Journal/32.shtml",
    "http://www.cqvip.com/Journal/33.shtml",
    "http://www.cqvip.com/Journal/34.shtml",
    "http://www.cqvip.com/Journal/35.shtml",
    "http://www.cqvip.com/Journal/36.shtml",
    "http://www.cqvip.com/Journal/37.shtml",
    "http://www.cqvip.com/Journal/38.shtml",

    "http://www.cqvip.com/Journal/52.shtml",
    "http://www.cqvip.com/Journal/53.shtml",
    "http://www.cqvip.com/Journal/54.shtml",
    "http://www.cqvip.com/Journal/55.shtml",
    "http://www.cqvip.com/Journal/56.shtml",
    "http://www.cqvip.com/Journal/57.shtml",
    "http://www.cqvip.com/Journal/58.shtml",
    "http://www.cqvip.com/Journal/59.shtml",
    "http://www.cqvip.com/Journal/60.shtml",
    "http://www.cqvip.com/Journal/61.shtml",
    "http://www.cqvip.com/Journal/62.shtml",

    "http://www.cqvip.com/Journal/48.shtml",
    "http://www.cqvip.com/Journal/49.shtml",
    "http://www.cqvip.com/Journal/50.shtml",
    "http://www.cqvip.com/Journal/51.shtml",
    "http://www.cqvip.com/Journal/70.shtml",

    "http://www.cqvip.com/Journal/39.shtml",
    "http://www.cqvip.com/Journal/40.shtml",
    "http://www.cqvip.com/Journal/41.shtml",
    "http://www.cqvip.com/Journal/42.shtml",
    "http://www.cqvip.com/Journal/43.shtml",
    "http://www.cqvip.com/Journal/44.shtml",
    "http://www.cqvip.com/Journal/45.shtml",
    "http://www.cqvip.com/Journal/46.shtml",
    "http://www.cqvip.com/Journal/47.shtml",
    "http://www.cqvip.com/Journal/69.shtml",
);

?>

